name: pocketses
base: core22
version: '0.1'
license: MIT
summary: What has it got in its pocketses, precious?!
description: |
  Learning about Snaps & Snapcraft

grade: stable
confinement: strict

apps:
  pocketses:
    command: bin/pocketses-cli
    plugs:
      - system-observe
      - network-observe

parts:
  pocketses:
    plugin: python
    source: .
    parse-info:
      - "setup.py"
    python-requirements:
      - requirements.txt
