name: pocketses
base: core22
version: "0.2.0"
license: MIT
summary: What has it got in its pocketses, precious?!
description: |
  Learning about Snaps & Snapcraft

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386

apps:
  pocketses:
    command: bin/pocketses-cli
    plugs:
      - system-observe
      - network-observe
      - network-bind

parts:
  pocketses:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-requirements:
      - requirements.txt
