name: pocketses
base: core22
version: '0.1'
license: MIT
summary: What has it got in its pocketses, precious?!
description: |
  Learning about Snaps & Snapcraft

grade: stable
confinement: strict

apps:
  pocketses:
    command: hello.sh
  bash:
    command: usr/local/bin/bash

parts:
  pocketses:
    source: pocketses
    plugin: dump

  gnu-bash:
      source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
      plugin: autotools
